/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c6c6c6',
        'on-tertiary': '#e2e2e2',
        'surface-dim': '#dadada',
        'inverse-surface': '#2f3131',
        'surface-tint': '#5e5e5e',
        'on-secondary-container': '#1b1b1b',
        'surface-container-high': '#e8e8e8',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#3b3b3b',
        'on-secondary-fixed': '#1b1b1b',
        'on-surface-variant': '#474747',
        'inverse-on-surface': '#f1f1f1',
        'on-primary-fixed-variant': '#e2e2e2',
        'tertiary-fixed': '#5e5e5e',
        'on-secondary': '#ffffff',
        'tertiary-container': '#747474',
        'surface-container-lowest': '#ffffff',
        surface: '#f9f9f9',
        'on-primary': '#e2e2e2',
        'primary-fixed': '#5e5e5e',
        'surface-container': '#eeeeee',
        'on-background': '#1a1c1c',
        'inverse-primary': '#c6c6c6',
        'secondary-fixed': '#c6c6c6',
        primary: '#000000',
        'surface-container-low': '#f3f3f3',
        'primary-fixed-dim': '#474747',
        'on-tertiary-fixed-variant': '#e2e2e2',
        'primary-container': '#3b3b3b',
        'surface-container-highest': '#e2e2e2',
        'tertiary-fixed-dim': '#474747',
        outline: '#777777',
        tertiary: '#3b3b3b',
        'surface-variant': '#e2e2e2',
        'on-primary-fixed': '#ffffff',
        'on-error': '#ffffff',
        'on-error-container': '#410002',
        'surface-bright': '#f9f9f9',
        secondary: '#5e5e5e',
        'on-tertiary-container': '#ffffff',
        'secondary-container': '#d4d4d4',
        'on-surface': '#1a1c1c',
        background: '#f9f9f9',
        'secondary-fixed-dim': '#ababab',
        'on-tertiary-fixed': '#ffffff',
        'on-primary-container': '#ffffff',
        error: '#ba1a1a',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
